name: 'Auto assign pull request to author'
description: 'Automatically assigns pull requests to their authors, excluding bot-created PRs'
author: 'bodyazinchenko'

inputs:
  github_token:
    default: '${{ github.token }}'
    required: true
    description: 'GitHub app installation access token.'

runs:
  using: 'node20'
  main: 'scripts/assign-pr-to-author.js'

branding:
  icon: 'user-plus'
  color: 'blue'