name: Test action
on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}